from . import area
from . import area_wise_branch
from . import attendance_delete
from . import attendance_lock
from . import attendance_range
from . import attendance_remark
from . import attendance_type
from . import ay_combination
from . import branch_mapping_with_division
from . import branch_section
from . import bulk_update
from . import combination_exam_course
from . import combination_faculty
from . import combination_sub_batch
from . import combinations
from . import course_group_batch_sub
from . import course_group_subjects
from . import define_holiday
from . import division
from . import et_wise_combination
from . import exam_branch_holiday
from . import exam_course
from . import exam_name
from . import exam_target
from . import exam_type
from . import hall_ticket
from . import holiday_entry
from . import institution_detail
from . import language_mapping
from . import lock_master
from . import new_sub_batch
from . import package_wise_sub_batch
from . import parent_feedback
from . import pic_combination_branch
from . import previous_course
from . import previous_course_previous_type
from . import previous_course_subject
from . import previous_type
from . import program_incharge
from . import results_upload
from . import section_teacher_subject
from . import section_wise_teacher
from . import sections
from . import special_batch
from . import student_info
from . import student_section_map
from . import student_wise_update
from . import sub_batch
from . import sub_batch_section
from . import sub_section
from . import sub_section_incharge_map
from . import sub_sub_batch
from . import sub_topic
from . import subject
from . import subject_order
from . import topics
from . import tracks
from . import university
from . import vc_parent_phone
