{
    'name': 'Pappaya Academic Management',
    'version': '11.0.1',
    'summary': 'Pappaya Academic Management',
    'description': 'Pappaya Academic Management',
    'category': 'Admission Management',
    'author': 'Think42labs',
    'website': 'https://www.think42labs.com',
    'depends': [
        'pappaya_base',
    ],
    'data': [
        'views/subject_views.xml',
        'wizard/batch_addition_view.xml',
        'wizard/batch_previous_courses_view.xml',
        'wizard/single_addition_view.xml',
        'wizard/subjects_view.xml',
        'wizard/tracks_view.xml',
        'wizard/topics_view.xml',
        'views/sections_views.xml',
        'wizard/sub_sub_batch_view.xml',
        'wizard/exam_name_view.xml',
        # 'wizard/previous_course_subject_view.xml',
        'wizard/language_mapping_view.xml',
        # 'views/tree_view_button.xml',
        'views/institution_detail_view.xml',
        'views/topics_views.xml',
        'views/previous_courses_view.xml',
        'views/previous_type_view.xml',
        'views/subject_order_view.xml',
        'views/ay_combination_view.xml',
        'views/combination_exam_course_view.xml',
        'views/et_wise_combination_view.xml',
        'views/area_wise_branch_view.xml',
        'views/branch_section_view.xml',
        'views/pic_combination_branch_view.xml',
        'views/result_upload_view.xml',
        'views/section_wise_teacher_view.xml',
        'views/vc_parent_phone_view.xml',
        'views/parent_feedback_view.xml',
        'views/bulk_update_view.xml',
        'views/section_teacher_subject_view.xml',
        'views/hall_ticket_view.xml',
        'views/student_info_view.xml',
        'views/student_wise_update_view.xml',
        'views/attendance_lock_view.xml',
        'views/attendance_range_view.xml',
        'views/attendance_delete_view.xml',
        'views/exam_branch_holiday.xml',
        'views/define_holiday_view.xml',
        'wizard/attendance_remark_view.xml',
        'wizard/attendance_type_view.xml',
        'wizard/holiday_entry_view.xml',
        'wizard/previous_course_view.xml',
        'wizard/previous_type_view.xml',
        'wizard/combination_master_view.xml',
        'wizard/sub_batch_view.xml',
        'wizard/special_batch_view.xml',
        'wizard/university_view.xml',
        'wizard/exam_course_view.xml',
        'wizard/sub_section_view.xml',
        'wizard/exam_target_view.xml',
        'wizard/area_view.xml',
        'wizard/program_incharge_view.xml',
        'wizard/sub_topic_view.xml',
        'wizard/exam_type_view.xml',
        'wizard/new_sub_batch_view.xml',
        'wizard/division_view.xml',
        'wizard/course_group_subjects_view.xml',
        'wizard/previous_course_previous_type_view.xml',
        'views/loac_lock_view.xml',
        'wizard/course_group_batch_sub_view.xml',
        'wizard/combination_sub_batch_view.xml',
        'views/branch_mapping_with_division_view.xml',
        'views/sub_section_incharge_map_view.xml',
        'wizard/combination_faculty_view.xml',
        'wizard/sub_batch_section_view.xml',
        'wizard/package_wise_sub_batch_view.xml',
        'views/student_section_map_view.xml',
        'views/branch_section_view.xml',
        'views/pic_combination_branch_view.xml',
        'views/result_upload_view.xml',
        'views/section_wise_teacher_view.xml',
        'views/vc_parent_phone_view.xml',
        'views/parent_feedback_view.xml',
        'views/bulk_update_view.xml',
        'views/section_teacher_subject_view.xml',
        'views/hall_ticket_view.xml',
        'views/student_info_view.xml',
        'views/student_wise_update_view.xml',
        'menu/pappaya_academic_menus.xml',
    ],
    'qweb': ['static/src/xml/many2many_checkboxes.xml'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
