# -*- coding: utf-8 -*-
{
    'name': 'Pappaya Base',
    'version': '11.0.2.4.0',
    'license': 'LGPL-3',
    'category': 'PappayaEd',
    "sequence": -20,
    'summary': 'Manage Educational Institution',
    'complexity': "easy",
    'description': """
        Description    ======
    """,
    'author': 'Think42Labs',
    'website': 'http://www.think42labs.com',
#     'depends': ['base', 'hr', 'mail', 'purchase', 'account', 'account_group_menu'],
    'depends': ['base', 'hr', 'hr_contract', 'hr_recruitment', 'mail', 'account', 
                'account_group_menu', 'utm','calendar','pappaya_operating_unit',
                'pappaya_org_chart_organization','pappaya_account_operating_unit',
                'pappaya_analytic_operating_unit','pappaya_sales_team_operating_unit'],
    'data': [
        # Demo Data
        'demo/company_demo.xml',
        'demo/user.xml',
        'demo/country.xml',
        'demo/currency_demo.xml',
        'demo/report_format.xml',
        'demo/hr_contract_data.xml',
        'demo/business_segment.xml',
        # Security
        'security/security.xml',
        'security/admission_security.xml',
        'security/ir.model.access.csv',
        # Global Masters
        'views/meta_data_master_view.xml',
        'views/fiscal_year_view.xml',
        'views/academic_year_view.xml',
        'views/common_masters/pappaya_master_view.xml',
        # Bank Details
        'views/bank/inherited_res_bank_view.xml',
        'views/bank/bank_account_branch_view.xml',
        'views/bank/bank_machine_view.xml',
        'views/bank/bank_machine_type_view.xml',
        # Common Master Configurations
        'views/common_masters/inherited_res_country_view.xml',
        'views/common_masters/inherited_res_country_state_view.xml',
        'views/common_masters/state_district_view.xml',
        'views/common_masters/community.xml',
        'views/common_masters/cluster_view.xml',
        'views/common_masters/material_view.xml',
        'views/common_masters/uniform_view.xml',
        'views/common_masters/branchwise_uniform_entry_view.xml',
        'views/common_masters/nslate_view.xml',
        'views/common_masters/deduction_view.xml',
        'views/common_masters/course_provider_view.xml',
        'views/common_masters/course_view.xml',
        # 'views/common_masters/department_master_view.xml',
        'views/common_masters/job_position_master_view.xml',

        'views/common_masters/group_view.xml',
        'views/common_masters/batch_view.xml',
        'views/common_masters/package_view.xml',
        'views/common_masters/business_segment_view.xml',
        'views/common_masters/caste_view.xml',
        'views/common_masters/religion_view.xml',
        'views/common_masters/medium_view.xml',
        'views/common_masters/course_package_view.xml',
        'views/common_masters/course_program_view.xml',
        'views/common_masters/zone_view.xml',
        'views/common_masters/batch_division_view.xml',
        'views/common_masters/lead_course_view.xml',
        'views/common_masters/pappaya_division.xml',
        'views/common_masters/pappaya_mandal_view.xml',
        'views/common_masters/pappaya_concession_view.xml',
        'views/common_masters/staff_type_view_hierarchy.xml',
        'views/common_masters/dhobi_provider_view.xml',
        # Transaction Related Master
        'views/common_masters/pay_mode_view.xml',
        # Admission Related Master
        'views/common_masters/student_type_view.xml',
        'views/common_masters/vc_view.xml',
        'views/common_masters/occupation_view.xml',
        'views/common_masters/additional_region_view.xml',
        'views/common_masters/unit_view.xml',
        'views/common_masters/unit_ic_view.xml',
        'views/common_masters/blood_group_view.xml',
        'views/common_masters/concession_type_view.xml',
        'views/common_masters/center_view.xml',
        'views/common_masters/pay_order_view.xml',
        'views/common_masters/sponsor_view.xml',
        'views/common_masters/other_fee_head_view.xml',
        'views/common_masters/status_view.xml',
        'views/common_masters/joinfrom_view.xml',
        # HR Related Master
        'views/common_masters/office_type_view.xml',
        'views/common_masters/work_hours_officetype_view.xml',
        'views/common_masters/legal_entity_view.xml',
        'views/common_masters/segment_view.xml',
        'views/common_masters/pappaya_stream_view.xml',
        
        'views/common_masters/programme_view.xml',
        'views/common_masters/class_view.xml',
        'views/common_masters/subject_view.xml',
        # Views/Masters
        'views/master/organization_view.xml',
        'views/master/entities_view.xml',
        'views/master/branch_view.xml',
        #Base
        'views/payroll_branch_view.xml',
        'views/inherited_res_company_view.xml',
        'views/geo_location_view.xml',
        'views/inherited_res_user_view.xml',
        'views/inherited_res_config_settings_view.xml',
        'views/inherited_accounts_view.xml',
        'views/organization_structure_view.xml',
        'views/attendance_history_table_view.xml',
        'views/calendar_generation_view.xml',
        'views/pappaya_calendar_view.xml',
        # 'views/transaction_table_for_oracle_view.xml',
        # Menu
        'menu/menu.xml',
        'menu/hide_print_menu.xml'
    ],
    'qweb': [
        'static/src/xml/client_action.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
