# -*- coding: utf-8 -*-
{
    'name': 'Pappaya Marketing',
    'version': '1.0',
    'category': 'Narayana Marketing',
    'sequence': -18,
    'summary': 'Pappaya',
    'author': 'Think42labs',
    'website': 'https://www.think42labs.com',
    'depends': ['base', 'hr', 'pappaya_base', 'pappaya_hr'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/division_inherit_view.xml',
        'views/lead_student_address_view.xml',
        'views/branch_target_view.xml',
        'views/expenditure_view.xml',
        'views/travelling_expenditure_proposal_view.xml',
        'views/incentive_view.xml',
        'views/res_user_view.xml',
        'views/target_view.xml',
        'views/staff_allocation_view.xml',
        'report/views/expenditure_proposal_report_pdf.xml',
        'report/address_collection_pdf.xml',
        'wizard/expenditure_proposal_report_wizard_view.xml',
        'wizard/address_collection_view.xml',
        'menu/menu.xml',
        'data/data.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'qweb': ['static/src/xml/report_address_collection.xml']
}