from . import area
from . import attendance_remark
from . import attendance_type
from . import batch_addition
from . import batch_previous_courses
from . import combination_faculty
from . import combination_master
from . import combination_sub_batch
from . import course_group_batch_sub
from . import course_group_subjects
from . import division
from . import exam_course
from . import exam_name
from . import exam_target
from . import exam_type
from . import holiday_entry
from . import language_mapping
from . import new_sub_batch
from . import package_wise_sub_batch
from . import previous_course
from . import previous_course_previous_type
from . import previous_course_subject
from . import previous_type
from . import program_incharge
from . import single_addition
from . import special_batch
from . import sub_batch
from . import sub_batch_section
from . import sub_section
from . import sub_sub_batch
from . import sub_topic
from . import subjects
from . import topics
from . import tracks
from . import university

